### ISSUE TITLE
Pushes to master included in changelog

### ISSUE THREAD

**Issue by hipstersmoothie** [intuit/auto-release#202]
**Is your feature request related to a problem? Please describe.**

Currently if i push to master it will create a patch release but it will not be added to the changelog

**Describe the solution you'd like**

These commits should be included in the changelog.

Beware merges and rebases though! We only want one changelog entry per changeset

**Comment by zephraph** [comment]
This is interesting... _should_ it create a release? At that point, we don't actually know what type of change has been made. I think on the whole we'd want to discourage this behavior because it's generally hard to trace. I'd almost prefer releases only happening when a merged PR w/ a particular label was found. 

I'm definitely 👍 about adding these changes to the changelog... but again, because we don't know specifically the type of changes that these are we'd likely want to group them into their own section.

**Comment by hipstersmoothie** [comment]
@adierkens weight in.

>  I'd almost prefer releases only happening when a merged PR w/ a particular label was found.

I'm kinda in this boat too. I like that every change has a PR. Adam knows of situations where this might be needed.

> because we don't know specifically the type of changes

It would always be a patch at this point but I'm open to it being in a special section

**Comment by adierkens** [comment]
> I'd almost prefer releases only happening when a merged PR w/ a particular label was found.

It's not something I'd encourage, but it's nice to be able to push a hot-fix to master when things break (like they did the other day when our Jenkins instance died half-way through a release). 

This wasn't an intentional thing -- we just defaulted the semver bump to `patch` when we went to calculate it, and since no PRs were included, we would generate a patch release. 

In the case that we only release when PRs are merged, does `auto version` return nothing? Throw an error? What happens when there _is_ a PR merged, but it doesn't have any semver labels?

Maybe this is a thing we should leave up to config -- specify in the `.autorc` what semver bump (or to skip the release) when we're unable to calculate one

**Comment by hipstersmoothie** [comment]
> I'd almost prefer releases only happening when a merged PR w/ a particular label was found.

this would be true in `onlyPublishWithReleaseLabel` mode. With that enabled pushed to master wouldn't create a release, but they would be included as patches on the changelog.
